#!/bin/bash
# Auto-generated by install.sh — do not edit paths by hand.
cd "/run/media/sword/F9EE-6FF0/windows/Study/Persona/Books/Extra_learnings/SwordFish" || exit 1
exec python3 "/run/media/sword/F9EE-6FF0/windows/Study/Persona/Books/Extra_learnings/SwordFish/src/main.py" "$@"
